# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-27 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('braggable', '0002_auto_20200227_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(null=True, upload_to='albums'),
        ),
    ]
